name: wellness_logger_mobile
description: Personal Wellness Logger - Mobile App for tracking SVT episodes, exercise, and medication

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  
  # Local Storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # UI & Navigation
  go_router: ^12.1.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  csv: ^5.0.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  
  # Charts & Analytics
  fl_chart: ^0.64.0
  
  # Development & Debugging
  logger: ^2.0.2+1
  get_it: ^7.6.4
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  
  # Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
